---

- hosts: forward
  roles:
    - role: neuropoly.sshtunnel
      tags: forward
      vars:
        is_forward: true
        sshtunnel_middlebox_ip: middlebox.host
        sshtunnel_privkey: "{{ lookup('file', 'example/middlebox') }}"
        sshtunnel_forward_home: "/srv/proxy"
        sshtunnel_forward_user: proxy
        sshtunnel_middlebox_user: proxy

- hosts: middlebox
  roles:
    - role: neuropoly.sshtunnel
      tags: middlebox
      vars:
        is_middlebox: true
        sshtunnel_guest_user: guestuser
        sshtunnel_guest_home: "/home/guestuser"
        sshtunnel_guest_pubkey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCee6aWkS5VvD6WXZk2aRMaY7mCZJCbzSF4qgWBQa5ptkqWwK5xjFyDvRmCgxj3aeOWt8uhrr4ai9wBsLMbMAuwKgC8thszy2HeMs7HqDfBqKcJJ76UVB0ZJB6vEQUD7SYTEEX09ODronY3lNFxEKA2Y330v6L3Dm45Cv3tyeUQEYOU83B2EiBAj1dAg+5GIHIi5lP6Lw+C35aW9mqn4unUpL/jDYN+Kf4u+QWLFjxToa1CrQgkK8AISvxgn5Hiq8uJeXljsivgU7Bzh89Ry1KGcOBzoVLCU/62UX81isOXLlP68SQSimHCLFmzxMIvInelqjFKEtno09XcnrKg8ZR670DOwP99P19gTIwpj61djzc5aKpcOuJ/N6Yt7jhXnwyu27vcG92aFy04JOuR7jfEkyVmZe3JxrLJ+GbkRR8uwbTbf1rJc5iYA6EThos59h0Qmy5vTrlN/hrMIbpsmMvQjhnhW6MbT1WqsBXc3/wQlJuI/pZc51Wpil80vC99sIE="
        sshtunnel_middlebox_user: proxy
        sshtunnel_middlebox_home: "/srv/proxy"
        sshtunnel_pubkey: "{{ lookup('file', 'example/middlebox.pub') }}"
