---

- name: Create forward_user account
  ansible.builtin.user:
    comment: "sshtunnel_forward_user"
    create_home: true
    generate_ssh_key: false
    home: "{{ sshtunnel_forward_home }}"
    name: "{{ sshtunnel_forward_user }}"
    # password: "*"
    shell: "{{ sshtunnel_shell }}"
    state: present
    
- name: Mkdir
  ansible.builtin.file:
    path: "{{ sshtunnel_forward_home }}/.ssh/"
    owner: "{{ sshtunnel_forward_user }}"
    state: directory

- name: Place sshtunnel private key for forward_user
  ansible.builtin.copy:
    # newline wasn't in my generated privkey but seems necessary?
    content: "{{ sshtunnel_privkey }}\n"
    dest: "{{ sshtunnel_forward_home }}/.ssh/id_rsa"
    owner: "{{ sshtunnel_forward_user }}"
    group: "{{ sshtunnel_forward_user }}"
    mode: "0600"
    
- name: Create the proxying systemd unit
  ansible.builtin.template:
    src: templates/sshtunnel.service.j2
    dest: /etc/systemd/system/sshtunnel.service

- name: Start the proxying systemd unit
  ansible.builtin.systemd_service:
    name: sshtunnel.service
    state: started
    enabled: true
    daemon_reload: true
