---

- name: Create middlebox_user account on middlebox
  ansible.builtin.user:
    comment: "sshtunnel_middlebox_user"
    create_home: true
    generate_ssh_key: false
    home: "{{ sshtunnel_middlebox_home }}"
    name: "{{ sshtunnel_middlebox_user }}"
    # password: "*"
    shell: "{{ sshtunnel_shell }}"
    state: present

- name: Create guest account on middlebox
  ansible.builtin.user:
    comment: "sshtunnel guest user"
    create_home: true
    generate_ssh_key: false
    # password: "*"
    home: "{{ sshtunnel_middlebox_home }}"
    name: "{{ sshtunnel_guest_user }}"
    shell: "{{ sshtunnel_shell }}"
    state: present

- name: Add guest sshkey to middlebox
  ansible.posix.authorized_key:
    user: "{{ sshtunnel_guest_user }}"
    key: "{{ sshtunnel_guest_pubkey }}"
    key_options: 'permitopen="localhost:2222",no-pty'
    state: present

- name: Override middlebox_user authorized_keys with forward's pubkey
  ansible.posix.authorized_key:
    user: "{{ sshtunnel_middlebox_user }}"
    key: "{{ sshtunnel_pubkey }}"
    exclusive: true
    state: present

